#!/usr/bin/env bash
# carbon-claude-brain — lib-carbon-brain.sh
# Funções helper compartilhadas entre hooks

# Carrega configuração de .env (ou config antigo para compatibilidade)
load_config() {
  local ENV_FILE="$HOME/.carbon-brain/.env"
  local OLD_CONFIG="$HOME/.carbon-brain/config"

  # Preferir .env (novo)
  if [ -f "$ENV_FILE" ]; then
    # Carregar .env (exportar variáveis)
    set -a
    source "$ENV_FILE"
    set +a
    return 0
  # Fallback para config antigo
  elif [ -f "$OLD_CONFIG" ]; then
    source "$OLD_CONFIG"
    return 0
  else
    return 1
  fi
}

# Loga erro
log_error() {
  local ERROR_LOG="$HOME/.carbon-brain/errors.log"
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" >> "$ERROR_LOG"
}

# Verifica se Inkdrop está configurado (URL + credenciais)
is_inkdrop_enabled() {
  if [ -z "$INKDROP_URL" ] || [ -z "$INKDROP_USER" ] || [ -z "$INKDROP_PASS" ]; then
    return 1  # Não configurado completamente
  fi
  return 0  # Habilitado
}

# Garante que o diretório de journals existe
ensure_global_journal_dir() {
  if [ -z "$OBSIDIAN_VAULT" ]; then
    log_error "ensure_global_journal_dir: OBSIDIAN_VAULT não está configurado"
    return 1
  fi

  local JOURNAL_DIR="$OBSIDIAN_VAULT/_claude-brain/global/journals"

  if ! mkdir -p "$JOURNAL_DIR" 2>/dev/null; then
    log_error "ensure_global_journal_dir: Falha ao criar diretório $JOURNAL_DIR"
    return 1
  fi

  if [ ! -d "$JOURNAL_DIR" ] || [ ! -w "$JOURNAL_DIR" ]; then
    log_error "ensure_global_journal_dir: Diretório $JOURNAL_DIR não é gravável"
    return 1
  fi

  echo "$JOURNAL_DIR"
  return 0
}

# Salva no Obsidian (SEMPRE)
save_to_obsidian_journal() {
  local PROJECT_NAME="$1"
  local DATE="$2"
  local START_TIME="$3"
  local END_TIME="$4"
  local CONTENT="$5"

  local JOURNAL_DIR
  if ! JOURNAL_DIR=$(ensure_global_journal_dir); then
    log_error "save_to_obsidian_journal: Falha ao criar diretório de journals"
    return 1
  fi

  local JOURNAL_FILE="$JOURNAL_DIR/$DATE.md"

  # Se arquivo existe para hoje, append
  if [ -f "$JOURNAL_FILE" ]; then
    if ! cat >> "$JOURNAL_FILE" <<EOF
---

## Session $START_TIME - $END_TIME
**Project:** $PROJECT_NAME

$CONTENT
EOF
    then
      log_error "save_to_obsidian_journal: Falha ao adicionar em $JOURNAL_FILE"
      return 1
    fi
  else
    # Criar novo arquivo
    if ! cat > "$JOURNAL_FILE" <<EOF
---
date: $DATE
tags: [session-journal, claude]
---

# Session Journal — $DATE

## Session $START_TIME - $END_TIME
**Project:** $PROJECT_NAME

$CONTENT

---
*Generated by carbon-claude-brain*
EOF
    then
      log_error "save_to_obsidian_journal: Falha ao criar $JOURNAL_FILE"
      return 1
    fi
  fi

  # Verificar que o arquivo foi escrito
  if [ ! -f "$JOURNAL_FILE" ] || [ ! -s "$JOURNAL_FILE" ]; then
    log_error "save_to_obsidian_journal: Arquivo $JOURNAL_FILE vazio ou ausente após escrita"
    return 1
  fi

  return 0
}

# Salva no Inkdrop (SE CONFIGURADO)
# Uma nota por dia - faz append se já existir
save_to_inkdrop_journal() {
  local PROJECT_NAME="$1"
  local DATE="$2"
  local START_TIME="$3"
  local END_TIME="$4"
  local CONTENT="$5"

  # Verificar se Inkdrop está habilitado
  if ! is_inkdrop_enabled; then
    return 0  # Não é erro, apenas skip
  fi

  # Buscar se já existe nota do dia
  local TITLE="Journal $PROJECT_NAME — $DATE"
  local SEARCH_RESPONSE
  SEARCH_RESPONSE=$(curl -s --max-time 5 \
    -u "$INKDROP_USER:$INKDROP_PASS" \
    "$INKDROP_URL/notes?keyword=$(echo "$TITLE" | sed 's/ /%20/g')&limit=50" 2>&1)

  local CURL_EXIT=$?
  if [ $CURL_EXIT -ne 0 ]; then
    log_error "brain-save: Failed to search Inkdrop (curl exit: $CURL_EXIT)"
    return 1
  fi

  # Parsear resposta para encontrar nota exata do dia
  local EXISTING_NOTE_ID
  local EXISTING_BODY

  EXISTING_NOTE_ID=$(echo "$SEARCH_RESPONSE" | SEARCH_TITLE="$TITLE" node -e "
    try {
      const title = process.env.SEARCH_TITLE;
      const data = JSON.parse(require('fs').readFileSync('/dev/stdin', 'utf8'));

      if (data.error) {
        console.error('Inkdrop API error: ' + data.error);
        process.exit(1);
      }

      const items = data.items || [];
      const exactMatch = items.find(note => note.title === title);
      if (exactMatch) {
        console.log(exactMatch._id);
      }
    } catch (e) {
      console.error('Failed to parse Inkdrop response: ' + e.message);
      process.exit(1);
    }
  " 2>&1)

  local NODE_EXIT=$?
  if [ $NODE_EXIT -ne 0 ]; then
    log_error "brain-save: Failed to parse search response: $EXISTING_NOTE_ID"
    return 1
  fi

  if [ -n "$EXISTING_NOTE_ID" ]; then
    # Já existe - buscar conteúdo completo
    EXISTING_BODY=$(echo "$SEARCH_RESPONSE" | SEARCH_TITLE="$TITLE" node -e "
      try {
        const title = process.env.SEARCH_TITLE;
        const data = JSON.parse(require('fs').readFileSync('/dev/stdin', 'utf8'));
        const items = data.items || [];
        const exactMatch = items.find(note => note.title === title);
        if (exactMatch) {
          console.log(exactMatch.body);
        }
      } catch (e) {
        console.error('Failed to extract body: ' + e.message);
        process.exit(1);
      }
    " 2>&1)

    NODE_EXIT=$?
    if [ $NODE_EXIT -ne 0 ]; then
      log_error "brain-save: Failed to extract note body: $EXISTING_BODY"
      return 1
    fi

    # Fazer append do novo conteúdo
    local NEW_BODY="$EXISTING_BODY

---

## Session $START_TIME - $END_TIME

$CONTENT"

    # UPDATE da nota existente
    local UPDATE_RESPONSE
    UPDATE_RESPONSE=$(curl -s --max-time 5 \
      -u "$INKDROP_USER:$INKDROP_PASS" \
      -X PUT "$INKDROP_URL/notes/$EXISTING_NOTE_ID" \
      -H "Content-Type: application/json" \
      -d "{
        \"body\": $(echo "$NEW_BODY" | node -e "console.log(JSON.stringify(require('fs').readFileSync('/dev/stdin', 'utf8')))")
      }" 2>&1)

    CURL_EXIT=$?
    if [ $CURL_EXIT -ne 0 ]; then
      log_error "brain-save: Failed to update Inkdrop note (curl exit: $CURL_EXIT)"
      return 1
    fi

    if echo "$UPDATE_RESPONSE" | grep -q '"_id"'; then
      return 0
    else
      log_error "brain-save: Inkdrop update error: $UPDATE_RESPONSE"
      return 1
    fi

  else
    # Não existe - criar nova nota
    local INITIAL_BODY="# Session Journal — $DATE

## Session $START_TIME - $END_TIME

$CONTENT

---
*Generated by carbon-claude-brain*"

    local CREATE_RESPONSE
    CREATE_RESPONSE=$(curl -s --max-time 5 \
      -u "$INKDROP_USER:$INKDROP_PASS" \
      -X POST "$INKDROP_URL/notes" \
      -H "Content-Type: application/json" \
      -d "{
        \"title\": \"$TITLE\",
        \"body\": $(echo "$INITIAL_BODY" | node -e "console.log(JSON.stringify(require('fs').readFileSync('/dev/stdin', 'utf8')))"),
        \"tags\": [\"claude-journal\", \"$PROJECT_NAME\"]
      }" 2>&1)

    CURL_EXIT=$?
    if [ $CURL_EXIT -ne 0 ]; then
      log_error "brain-save: Failed to create Inkdrop note (curl exit: $CURL_EXIT)"
      return 1
    fi

    if echo "$CREATE_RESPONSE" | grep -q '"_id"'; then
      return 0
    else
      log_error "brain-save: Inkdrop create error: $CREATE_RESPONSE"
      return 1
    fi
  fi
}

# Salva aprendizado geral reutilizável no Obsidian
save_learning() {
  local CATEGORY="$1"
  local LEARNING="$2"

  if [ -z "$CATEGORY" ] || [ -z "$LEARNING" ]; then
    log_error "save_learning: CATEGORY e LEARNING são obrigatórios"
    return 1
  fi

  if [ -z "$OBSIDIAN_VAULT" ]; then
    log_error "save_learning: OBSIDIAN_VAULT não configurado"
    return 1
  fi

  local LEARNINGS_FILE="$OBSIDIAN_VAULT/_claude-brain/global/learnings.md"

  if [ ! -f "$LEARNINGS_FILE" ]; then
    log_error "save_learning: learnings.md não encontrado em $LEARNINGS_FILE"
    return 1
  fi

  if [ ! -w "$LEARNINGS_FILE" ]; then
    log_error "save_learning: learnings.md não é gravável"
    return 1
  fi

  # Usar awk para inserção segura (sem risco de shell injection)
  local TEMP_FILE="${LEARNINGS_FILE}.tmp.$$"

  if grep -q "^## $CATEGORY\$" "$LEARNINGS_FILE"; then
    # Categoria existe - adicionar após ela
    awk -v cat="## $CATEGORY" -v learning="- $LEARNING" '
      {print}
      $0 == cat {print learning}
    ' "$LEARNINGS_FILE" > "$TEMP_FILE"
  else
    # Categoria não existe - criar antes do footer
    awk -v cat="## $CATEGORY" -v learning="- $LEARNING" '
      /^---$/ && !done {
        print cat
        print learning
        print ""
        done=1
      }
      {print}
    ' "$LEARNINGS_FILE" > "$TEMP_FILE"
  fi

  # Substituir atomicamente
  if ! mv "$TEMP_FILE" "$LEARNINGS_FILE"; then
    log_error "save_learning: Falha ao atualizar learnings.md"
    rm -f "$TEMP_FILE"
    return 1
  fi

  return 0
}

# Salva erro resolvido no Obsidian
save_error_solved() {
  local DATE="$1"
  local ERROR_TITLE="$2"
  local CONTEXT="$3"
  local ERROR_MSG="$4"
  local SOLUTION="$5"
  local PREVENTION="$6"

  if [ -z "$DATE" ] || [ -z "$ERROR_TITLE" ] || [ -z "$CONTEXT" ] || \
     [ -z "$ERROR_MSG" ] || [ -z "$SOLUTION" ] || [ -z "$PREVENTION" ]; then
    log_error "save_error_solved: Todos os 6 parâmetros são obrigatórios"
    return 1
  fi

  if [ -z "$OBSIDIAN_VAULT" ]; then
    log_error "save_error_solved: OBSIDIAN_VAULT não configurado"
    return 1
  fi

  local ERRORS_FILE="$OBSIDIAN_VAULT/_claude-brain/global/errors-solved.md"

  if [ ! -f "$ERRORS_FILE" ]; then
    log_error "save_error_solved: errors-solved.md não encontrado em $ERRORS_FILE"
    return 1
  fi

  if [ ! -w "$ERRORS_FILE" ]; then
    log_error "save_error_solved: errors-solved.md não é gravável"
    return 1
  fi

  # Usar arquivo temporário para escrita segura
  local TEMP_FILE="${ERRORS_FILE}.tmp.$$"

  # Adicionar antes da primeira linha "---"
  awk -v date="$DATE" -v title="$ERROR_TITLE" -v ctx="$CONTEXT" \
      -v err="$ERROR_MSG" -v sol="$SOLUTION" -v prev="$PREVENTION" '
    /^---$/ && !done {
      print "### [" date "] Erro: " title
      print "- **Contexto:** " ctx
      print "- **Erro:** " err
      print "- **Solução:** " sol
      print "- **Prevenção:** " prev
      print ""
      print ""
      done=1
    }
    {print}
  ' "$ERRORS_FILE" > "$TEMP_FILE"

  # Substituir atomicamente
  if ! mv "$TEMP_FILE" "$ERRORS_FILE"; then
    log_error "save_error_solved: Falha ao atualizar errors-solved.md"
    rm -f "$TEMP_FILE"
    return 1
  fi

  return 0
}
